import type { BigDealCard } from '../types/index.js';

export const BIG_DEAL_CARDS: BigDealCard[] = [
  // ── 8-Plex Properties ──
  {
    id: 'bd-1',
    title: '8-Plex - Blue Collar Area',
    deal: {
      type: 'realEstate',
      subType: 'eightplex',
      name: '8-Plex - Blue Collar Area',
      cost: 220000,
      mortgage: 180000,
      downPayment: 40000,
      cashFlow: 1700,
      description: 'Eight-unit building near industrial park. Reliable tenants.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-2',
    title: '8-Plex - Renovated',
    deal: {
      type: 'realEstate',
      subType: 'eightplex',
      name: '8-Plex - Renovated',
      cost: 160000,
      mortgage: 128000,
      downPayment: 32000,
      cashFlow: 1700,
      description: 'Recently renovated 8-unit building. Great cash flow.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-3',
    title: '8-Plex - Needs Work',
    deal: {
      type: 'realEstate',
      subType: 'eightplex',
      name: '8-Plex - Needs Work',
      cost: 240000,
      mortgage: 200000,
      downPayment: 40000,
      cashFlow: 950,
      description: 'Older 8-unit building. Needs some repairs but tenants in place.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },

  // ── 4-Plex Properties ──
  {
    id: 'bd-4',
    title: '4-Plex - Starter Investment',
    deal: {
      type: 'realEstate',
      subType: 'fourplex',
      name: '4-Plex - Starter Investment',
      cost: 80000,
      mortgage: 64000,
      downPayment: 16000,
      cashFlow: 750,
      description: 'Four-unit building. Great entry into multi-unit investing.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-5',
    title: '4-Plex - Near Mall',
    deal: {
      type: 'realEstate',
      subType: 'fourplex',
      name: '4-Plex - Near Mall',
      cost: 90000,
      mortgage: 75000,
      downPayment: 15000,
      cashFlow: 500,
      description: 'Convenient location near shopping center.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-6',
    title: '4-Plex - Premium Location',
    deal: {
      type: 'realEstate',
      subType: 'fourplex',
      name: '4-Plex - Premium Location',
      cost: 140000,
      mortgage: 108000,
      downPayment: 32000,
      cashFlow: 2000,
      description: 'Four units in a prime area. Outstanding cash flow.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-7',
    title: '4-Plex - Budget Deal',
    deal: {
      type: 'realEstate',
      subType: 'fourplex',
      name: '4-Plex - Budget Deal',
      cost: 80000,
      mortgage: 60000,
      downPayment: 20000,
      cashFlow: 400,
      description: 'Four-unit building at a budget price. Modest cash flow.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-8',
    title: '4-Plex - Growing Area',
    deal: {
      type: 'realEstate',
      subType: 'fourplex',
      name: '4-Plex - Growing Area',
      cost: 125000,
      mortgage: 110000,
      downPayment: 15000,
      cashFlow: 600,
      description: 'Four-unit property in a rapidly growing neighborhood.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },

  // ── Duplex Properties ──
  {
    id: 'bd-9',
    title: 'Duplex - Working Class',
    deal: {
      type: 'realEstate',
      subType: 'duplex',
      name: 'Duplex - Working Class',
      cost: 60000,
      mortgage: 48000,
      downPayment: 12000,
      cashFlow: 400,
      description: 'Two-unit duplex in a working-class area.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-10',
    title: 'Duplex - Bargain',
    deal: {
      type: 'realEstate',
      subType: 'duplex',
      name: 'Duplex - Bargain',
      cost: 45000,
      mortgage: 37000,
      downPayment: 8000,
      cashFlow: 320,
      description: 'Affordable duplex with solid rental history.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },

  // ── 3Br/2Ba Houses (Big Deal size) ──
  {
    id: 'bd-11',
    title: '3Br/2Ba - Executive Home',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba - Executive Home',
      cost: 70000,
      mortgage: 50000,
      downPayment: 20000,
      cashFlow: 500,
      description: 'Upscale 3Br/2Ba in a desirable neighborhood.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-12',
    title: '3Br/2Ba - Good Cash Flow',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba - Good Cash Flow',
      cost: 65000,
      mortgage: 57000,
      downPayment: 8000,
      cashFlow: 300,
      description: 'Low down payment with decent cash flow.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-13',
    title: '3Br/2Ba - Negative Cash Flow!',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba - Overpriced',
      cost: 125000,
      mortgage: 105000,
      downPayment: 20000,
      cashFlow: -100,
      description: 'Overpriced house with negative monthly cash flow. Bad deal!',
      rule: 'Pay the down payment. Warning: this property loses money each month!',
    },
  },

  // ── Large Apartment Complexes ──
  {
    id: 'bd-14',
    title: '24-Unit Apartment Building',
    deal: {
      type: 'realEstate',
      subType: 'apartment',
      name: '24-Unit Apartment Building',
      cost: 575000,
      mortgage: 500000,
      downPayment: 75000,
      cashFlow: 3400,
      description: '24-unit apartment complex. Major cash flow generator.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-15',
    title: '12-Unit Apartment Complex',
    deal: {
      type: 'realEstate',
      subType: 'apartment',
      name: '12-Unit Apartment Complex',
      cost: 350000,
      mortgage: 300000,
      downPayment: 50000,
      cashFlow: 2400,
      description: '12-unit complex. Excellent passive income.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-16',
    title: '60-Unit Apartment Complex',
    deal: {
      type: 'realEstate',
      subType: 'apartment',
      name: '60-Unit Apartment Complex',
      cost: 1200000,
      mortgage: 1000000,
      downPayment: 200000,
      cashFlow: 11000,
      description: 'Massive 60-unit complex. The ultimate passive income property.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },

  // ── Business Deals ──
  {
    id: 'bd-17',
    title: 'Pizza Franchise',
    deal: {
      type: 'business',
      name: 'Pizza Franchise',
      cost: 500000,
      mortgage: 400000,
      downPayment: 100000,
      cashFlow: 5000,
      description: 'Well-known pizza franchise. Turnkey operation with high cash flow.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-18',
    title: '4-Bay Auto Wash',
    deal: {
      type: 'business',
      name: '4-Bay Auto Wash',
      cost: 125000,
      mortgage: 100000,
      downPayment: 25000,
      cashFlow: 1800,
      description: 'Automated car wash business. Minimal labor costs.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-19',
    title: 'Car Wash Chain',
    deal: {
      type: 'business',
      name: 'Car Wash Chain',
      cost: 350000,
      mortgage: 300000,
      downPayment: 50000,
      cashFlow: 1500,
      description: 'Multi-location car wash business.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-20',
    title: 'Bed & Breakfast',
    deal: {
      type: 'business',
      name: 'Bed & Breakfast',
      cost: 150000,
      mortgage: 120000,
      downPayment: 30000,
      cashFlow: 1000,
      description: 'Charming B&B in a tourist area. Seasonal but profitable.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },

  // ── Limited Partnerships (No Mortgage) ──
  {
    id: 'bd-21',
    title: 'Sandwich Shop Partnership',
    deal: {
      type: 'business',
      name: 'Sandwich Shop Partnership',
      cost: 30000,
      mortgage: 0,
      downPayment: 30000,
      cashFlow: 1500,
      description: 'Limited partnership in a successful sandwich franchise.',
      rule: 'Pay the full cost. No mortgage - you own your share outright.',
    },
  },
  {
    id: 'bd-22',
    title: 'Auto Dealership Partnership',
    deal: {
      type: 'business',
      name: 'Auto Dealership Partnership',
      cost: 30000,
      mortgage: 0,
      downPayment: 30000,
      cashFlow: 1000,
      description: 'Limited partnership in a used car dealership.',
      rule: 'Pay the full cost. No mortgage - you own your share outright.',
    },
  },

  // ── Vacant Land ──
  {
    id: 'bd-23',
    title: '20-Acre Vacant Land',
    deal: {
      type: 'realEstate',
      subType: 'land',
      name: '20-Acre Vacant Land',
      cost: 20000,
      mortgage: 0,
      downPayment: 20000,
      cashFlow: 0,
      description: 'Raw land in path of city growth. No cash flow but potential for appreciation.',
      rule: 'Pay the full cost. No cash flow until sold.',
    },
  },

  // ── 3Br/2Ba - Another House Option ──
  {
    id: 'bd-24',
    title: '3Br/2Ba - Modest Deal',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba - Modest Deal',
      cost: 65000,
      mortgage: 58000,
      downPayment: 7000,
      cashFlow: 150,
      description: 'Modest home with low cash flow but low entry cost.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
];
