import type { BigDealCard } from '../types/index.js';

export const BIG_DEAL_CARDS: BigDealCard[] = [
  // ── Large Real Estate Deals ──
  {
    id: 'bd-1',
    title: '24-Unit Apartment Building',
    deal: {
      type: 'realEstate',
      subType: 'apartment',
      name: '24-Unit Apartment Building',
      cost: 500000,
      mortgage: 450000,
      downPayment: 50000,
      cashFlow: 2600,
      description: '24-unit apartment complex in growing suburb. 90% occupancy rate.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-2',
    title: '12-Unit Apartment Complex',
    deal: {
      type: 'realEstate',
      subType: 'apartment',
      name: '12-Unit Apartment Complex',
      cost: 300000,
      mortgage: 270000,
      downPayment: 30000,
      cashFlow: 1500,
      description: '12-unit complex near university. Student housing generates steady income.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-3',
    title: '8-Plex - Blue Collar Area',
    deal: {
      type: 'realEstate',
      subType: 'eightplex',
      name: '8-Plex - Blue Collar Area',
      cost: 200000,
      mortgage: 175000,
      downPayment: 25000,
      cashFlow: 1000,
      description: 'Eight-unit building near industrial park. Reliable working-class tenants.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-4',
    title: '8-Plex - Renovated',
    deal: {
      type: 'realEstate',
      subType: 'eightplex',
      name: '8-Plex - Renovated',
      cost: 280000,
      mortgage: 250000,
      downPayment: 30000,
      cashFlow: 1400,
      description: 'Recently renovated 8-unit building. New plumbing and electrical.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-5',
    title: 'Commercial Strip Mall',
    deal: {
      type: 'realEstate',
      subType: 'commercial',
      name: 'Commercial Strip Mall',
      cost: 400000,
      mortgage: 350000,
      downPayment: 50000,
      cashFlow: 2200,
      description: 'Six-unit strip mall on busy intersection. Long-term commercial leases.',
      rule: 'Pay the down payment from your savings. Commercial mortgage covers the balance.',
    },
  },
  {
    id: 'bd-6',
    title: 'Office Building - Downtown',
    deal: {
      type: 'realEstate',
      subType: 'commercial',
      name: 'Office Building - Downtown',
      cost: 450000,
      mortgage: 400000,
      downPayment: 50000,
      cashFlow: 2000,
      description: 'Three-story office building in central business district.',
      rule: 'Pay the down payment from your savings. Commercial mortgage covers the balance.',
    },
  },
  {
    id: 'bd-7',
    title: '4-Plex - Upscale Area',
    deal: {
      type: 'realEstate',
      subType: 'fourplex',
      name: '4-Plex - Upscale Area',
      cost: 160000,
      mortgage: 140000,
      downPayment: 20000,
      cashFlow: 800,
      description: 'Four-unit building in upscale neighborhood. Premium rents.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-8',
    title: '4-Plex - Near Mall',
    deal: {
      type: 'realEstate',
      subType: 'fourplex',
      name: '4-Plex - Near Mall',
      cost: 180000,
      mortgage: 155000,
      downPayment: 25000,
      cashFlow: 900,
      description: 'Four-unit property near shopping center. Convenient location attracts tenants.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-9',
    title: '20-Acre Vacant Land',
    deal: {
      type: 'realEstate',
      subType: 'land',
      name: '20-Acre Vacant Land',
      cost: 150000,
      mortgage: 120000,
      downPayment: 30000,
      cashFlow: 0,
      description: 'Raw land in path of city growth. No cash flow but potential for appreciation.',
      rule: 'Pay the down payment from your savings. Land loan covers the balance. No cash flow until sold.',
    },
  },
  {
    id: 'bd-10',
    title: 'Warehouse - Industrial District',
    deal: {
      type: 'realEstate',
      subType: 'commercial',
      name: 'Warehouse - Industrial District',
      cost: 250000,
      mortgage: 220000,
      downPayment: 30000,
      cashFlow: 1300,
      description: 'Large warehouse leased to distribution company. Triple-net lease.',
      rule: 'Pay the down payment from your savings. Commercial mortgage covers the balance.',
    },
  },
  {
    id: 'bd-11',
    title: '30-Unit Apartment Complex',
    deal: {
      type: 'realEstate',
      subType: 'apartment',
      name: '30-Unit Apartment Complex',
      cost: 500000,
      mortgage: 420000,
      downPayment: 80000,
      cashFlow: 3200,
      description: '30-unit garden-style apartments. On-site laundry and parking.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-12',
    title: '16-Unit Apartment Building',
    deal: {
      type: 'realEstate',
      subType: 'apartment',
      name: '16-Unit Apartment Building',
      cost: 350000,
      mortgage: 310000,
      downPayment: 40000,
      cashFlow: 1800,
      description: 'Well-maintained 16-unit building. Recently passed all inspections.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-13',
    title: 'Retail Plaza',
    deal: {
      type: 'realEstate',
      subType: 'commercial',
      name: 'Retail Plaza',
      cost: 480000,
      mortgage: 400000,
      downPayment: 80000,
      cashFlow: 2800,
      description: 'Retail plaza anchored by grocery store. 95% occupied.',
      rule: 'Pay the down payment from your savings. Commercial mortgage covers the balance.',
    },
  },
  {
    id: 'bd-14',
    title: '10-Acre Development Land',
    deal: {
      type: 'realEstate',
      subType: 'land',
      name: '10-Acre Development Land',
      cost: 200000,
      mortgage: 160000,
      downPayment: 40000,
      cashFlow: 0,
      description: 'Zoned for residential development. Utilities already at property line.',
      rule: 'Pay the down payment from your savings. No cash flow until developed or sold.',
    },
  },

  // ── Big Business Deals ──
  {
    id: 'bd-15',
    title: 'Franchise Restaurant',
    deal: {
      type: 'business',
      name: 'Franchise Restaurant',
      cost: 350000,
      mortgage: 280000,
      downPayment: 70000,
      cashFlow: 2500,
      description: 'Well-known fast food franchise in high-traffic location. Turnkey operation.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-16',
    title: 'Automated Car Wash Chain',
    deal: {
      type: 'business',
      name: 'Automated Car Wash Chain',
      cost: 300000,
      mortgage: 250000,
      downPayment: 50000,
      cashFlow: 1800,
      description: 'Three-location automated car wash business. Minimal labor costs.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-17',
    title: 'Laundromat Chain',
    deal: {
      type: 'business',
      name: 'Laundromat Chain',
      cost: 200000,
      mortgage: 160000,
      downPayment: 40000,
      cashFlow: 1200,
      description: 'Four self-service laundromats in residential neighborhoods.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-18',
    title: 'Gas Station & Convenience Store',
    deal: {
      type: 'business',
      name: 'Gas Station & Convenience Store',
      cost: 400000,
      mortgage: 320000,
      downPayment: 80000,
      cashFlow: 3000,
      description: 'Branded gas station with busy convenience store on highway exit.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-19',
    title: 'Self-Storage Facility',
    deal: {
      type: 'business',
      name: 'Self-Storage Facility',
      cost: 350000,
      mortgage: 300000,
      downPayment: 50000,
      cashFlow: 2000,
      description: '100-unit self-storage facility near residential area. 85% occupancy.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-20',
    title: 'Pizza Franchise - 3 Locations',
    deal: {
      type: 'business',
      name: 'Pizza Franchise - 3 Locations',
      cost: 450000,
      mortgage: 350000,
      downPayment: 100000,
      cashFlow: 5000,
      description: 'Three pizza franchise locations with delivery service. Strong brand recognition.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-21',
    title: '8-Plex - Gentrifying Neighborhood',
    deal: {
      type: 'realEstate',
      subType: 'eightplex',
      name: '8-Plex - Gentrifying Neighborhood',
      cost: 240000,
      mortgage: 210000,
      downPayment: 30000,
      cashFlow: 1200,
      description: 'Eight units in a neighborhood seeing rapid improvement. Rents rising.',
      rule: 'Pay the down payment from your savings. Mortgage covers the balance.',
    },
  },
  {
    id: 'bd-22',
    title: 'Mini Mall - Suburban',
    deal: {
      type: 'realEstate',
      subType: 'commercial',
      name: 'Mini Mall - Suburban',
      cost: 320000,
      mortgage: 280000,
      downPayment: 40000,
      cashFlow: 1600,
      description: 'Small suburban shopping center with salon, dry cleaner, and deli.',
      rule: 'Pay the down payment from your savings. Commercial mortgage covers the balance.',
    },
  },
  {
    id: 'bd-23',
    title: 'Gym Franchise',
    deal: {
      type: 'business',
      name: 'Gym Franchise',
      cost: 250000,
      mortgage: 200000,
      downPayment: 50000,
      cashFlow: 1500,
      description: 'Fitness center franchise in growing suburb. Monthly membership model.',
      rule: 'Pay the down payment from your savings. Business loan covers the balance.',
    },
  },
  {
    id: 'bd-24',
    title: 'Medical Office Building',
    deal: {
      type: 'realEstate',
      subType: 'commercial',
      name: 'Medical Office Building',
      cost: 380000,
      mortgage: 330000,
      downPayment: 50000,
      cashFlow: 2400,
      description: 'Medical office building near hospital. Long-term leases with doctors.',
      rule: 'Pay the down payment from your savings. Commercial mortgage covers the balance.',
    },
  },
];
