import type { DoodadCard } from '../types/index.js';

export const DOODAD_CARDS: DoodadCard[] = [
  {
    id: 'dd-1',
    title: 'New Boat',
    description: 'You just bought a new fishing boat. So much for saving money!',
    cost: 1000,
  },
  {
    id: 'dd-2',
    title: 'Jet Ski',
    description: 'Summer is here and you could not resist buying a jet ski.',
    cost: 1000,
  },
  {
    id: 'dd-3',
    title: 'Big Screen TV',
    description: 'That 85-inch TV was calling your name. Home theater complete!',
    cost: 4000,
  },
  {
    id: 'dd-4',
    title: 'Hawaiian Vacation',
    description: 'You booked a two-week vacation to Hawaii. Aloha to your savings!',
    cost: 3400,
  },
  {
    id: 'dd-5',
    title: 'Shopping Spree',
    description: 'You went to the mall and could not stop buying things.',
    cost: 800,
  },
  {
    id: 'dd-6',
    title: 'Car Repair',
    description: 'Your car broke down. Transmission needs to be replaced.',
    cost: 500,
  },
  {
    id: 'dd-7',
    title: 'Dental Work',
    description: 'Root canal and crown. Your insurance only covers half.',
    cost: 2000,
  },
  {
    id: 'dd-8',
    title: 'Speeding Ticket',
    description: 'You were caught going 20 over the limit. Pay the fine.',
    cost: 150,
  },
  {
    id: 'dd-9',
    title: 'New Phone',
    description: 'Your phone screen cracked. Time for the latest model, of course.',
    cost: 1200,
  },
  {
    id: 'dd-10',
    title: 'Charity Donation',
    description: 'You feel generous and donate 10% of your income to charity.',
    cost: 10,
    isPercentOfIncome: true,
  },
  {
    id: 'dd-11',
    title: 'Home Repair',
    description: 'Water heater broke. Need a new one installed immediately.',
    cost: 1500,
  },
  {
    id: 'dd-12',
    title: 'New Furniture',
    description: 'You redecorated the living room. New couch, table, and chairs.',
    cost: 3000,
  },
  {
    id: 'dd-13',
    title: 'Gym Equipment',
    description: 'You set up a home gym. Treadmill, weights, and bench.',
    cost: 2500,
  },
  {
    id: 'dd-14',
    title: 'Birthday Party',
    description: 'You threw an extravagant birthday party for your child.',
    cost: 400,
  },
  {
    id: 'dd-15',
    title: 'Traffic Accident',
    description: 'Fender bender in a parking lot. You pay for the damages.',
    cost: 1000,
  },
  {
    id: 'dd-16',
    title: 'New Wardrobe',
    description: 'You decided your closet needed a complete overhaul.',
    cost: 1500,
  },
  {
    id: 'dd-17',
    title: 'Dining Out',
    description: 'A month of eating at expensive restaurants adds up fast.',
    cost: 600,
  },
  {
    id: 'dd-18',
    title: 'Gambling Loss',
    description: 'Weekend trip to Las Vegas. You did not come out ahead.',
    cost: 3000,
  },
  {
    id: 'dd-19',
    title: 'Medical Emergency',
    description: 'Unexpected trip to the ER. Insurance deductible applies.',
    cost: 5000,
  },
  {
    id: 'dd-20',
    title: 'Parking Ticket',
    description: 'You forgot to feed the meter. Pay the fine.',
    cost: 75,
  },
  {
    id: 'dd-21',
    title: 'Pet Expenses',
    description: 'Your dog needed emergency surgery at the vet.',
    cost: 2000,
  },
  {
    id: 'dd-22',
    title: 'Concert Tickets',
    description: 'You splurged on front-row tickets to see your favorite band.',
    cost: 500,
  },
  {
    id: 'dd-23',
    title: 'New Laptop',
    description: 'Your old laptop died. You bought the top-of-the-line replacement.',
    cost: 2500,
  },
  {
    id: 'dd-24',
    title: 'Wedding Gift',
    description: 'Your best friend is getting married. You went all out on the gift.',
    cost: 1000,
  },
  {
    id: 'dd-25',
    title: 'Skiing Trip',
    description: 'Weekend ski trip with friends. Lift tickets, gear rental, and lodge.',
    cost: 1800,
  },
];
