import type { DoodadCard } from '../types/index.js';

export const DOODAD_CARDS: DoodadCard[] = [
  {
    id: 'dd-1',
    title: 'Jet Ski',
    description: 'Summer is here and you could not resist buying a jet ski.',
    cost: 3000,
  },
  {
    id: 'dd-2',
    title: 'Build a Home Gym',
    description: 'You set up a home gym. Treadmill, weights, and bench.',
    cost: 3000,
  },
  {
    id: 'dd-3',
    title: 'Big Screen TV',
    description: 'That 65-inch 4K TV was calling your name.',
    cost: 2500,
  },
  {
    id: 'dd-4',
    title: 'Family Vacation',
    description: 'You booked a week-long family vacation. Memories are priceless!',
    cost: 2500,
  },
  {
    id: 'dd-5',
    title: 'New Rims for Your Car',
    description: 'You decided your car needed some flashy new rims.',
    cost: 2000,
  },
  {
    id: 'dd-6',
    title: 'Golf Club Membership',
    description: 'You joined the local golf club. Annual dues paid upfront.',
    cost: 2000,
  },
  {
    id: 'dd-7',
    title: 'New Computer',
    description: 'Your old laptop died. You bought the top-of-the-line replacement.',
    cost: 1800,
  },
  {
    id: 'dd-8',
    title: 'Season Tickets',
    description: 'You bought season tickets to your favorite team.',
    cost: 1500,
  },
  {
    id: 'dd-9',
    title: 'New Sound System',
    description: 'You splurged on a premium surround sound system.',
    cost: 1500,
  },
  {
    id: 'dd-10',
    title: 'Wine Country Trip',
    description: 'Weekend getaway to wine country with friends.',
    cost: 1000,
  },
  {
    id: 'dd-11',
    title: 'New Tailored Suit',
    description: 'You got fitted for a custom tailored suit.',
    cost: 1000,
  },
  {
    id: 'dd-12',
    title: 'New Clothes',
    description: 'You decided your wardrobe needed a complete refresh.',
    cost: 1000,
  },
  {
    id: 'dd-13',
    title: 'Go to Casino',
    description: 'Weekend trip to the casino. You did not come out ahead.',
    cost: 800,
  },
  {
    id: 'dd-14',
    title: 'New Golf Clubs',
    description: 'You treated yourself to a new set of golf clubs.',
    cost: 800,
  },
  {
    id: 'dd-15',
    title: 'Replace Car AC',
    description: 'Your car air conditioner broke down. Had to get it replaced.',
    cost: 700,
  },
  {
    id: 'dd-16',
    title: 'Visit the Dentist',
    description: 'Root canal and crown. Your insurance only covers half.',
    cost: 700,
  },
  {
    id: 'dd-17',
    title: 'Next-Gen Game Console',
    description: 'You bought the latest gaming console and some games.',
    cost: 600,
  },
  {
    id: 'dd-18',
    title: 'Repaint Your House',
    description: 'Time to freshen up the exterior. You hired painters.',
    cost: 600,
  },
  {
    id: 'dd-19',
    title: 'New Tires',
    description: 'All four tires needed replacing. Safety first!',
    cost: 600,
  },
  {
    id: 'dd-20',
    title: 'Date Night',
    description: 'Fancy restaurant, show, and a limo. You went all out.',
    cost: 500,
  },
  {
    id: 'dd-21',
    title: 'High School Reunion',
    description: 'Travel and expenses for your high school reunion weekend.',
    cost: 500,
  },
  {
    id: 'dd-22',
    title: 'Custom Jewelry',
    description: 'You surprised someone special with custom jewelry.',
    cost: 400,
  },
  {
    id: 'dd-23',
    title: 'Get Newest Phone',
    description: 'Your phone screen cracked. Time for the latest model.',
    cost: 300,
  },
  {
    id: 'dd-24',
    title: 'Concert Tickets',
    description: 'You splurged on great seats to see your favorite band.',
    cost: 200,
  },
  {
    id: 'dd-25',
    title: 'New Wristwatch',
    description: 'You saw a nice watch in a store window and had to have it.',
    cost: 200,
  },
];
