import type { SmallDealCard } from '../types/index.js';

export const SMALL_DEAL_CARDS: SmallDealCard[] = [
  // ── Stock Deals: ON2U Entertainment ──
  // Real game: volatile biotech/entertainment stock, no dividend, range $5-$40
  {
    id: 'sd-1',
    title: 'ON2U Inc. - $5',
    deal: {
      type: 'stock',
      name: 'ON2U Inc.',
      symbol: 'ON2U',
      costPerShare: 5,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 40 },
      description: 'Entertainment company. Volatile price swings.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-2',
    title: 'ON2U Inc. - $10',
    deal: {
      type: 'stock',
      name: 'ON2U Inc.',
      symbol: 'ON2U',
      costPerShare: 10,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 40 },
      description: 'Entertainment company. Price is moderate.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-3',
    title: 'ON2U Inc. - $20',
    deal: {
      type: 'stock',
      name: 'ON2U Inc.',
      symbol: 'ON2U',
      costPerShare: 20,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 40 },
      description: 'Entertainment company. Price is near the high end.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-4',
    title: 'ON2U Inc. - $30',
    deal: {
      type: 'stock',
      name: 'ON2U Inc.',
      symbol: 'ON2U',
      costPerShare: 30,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 40 },
      description: 'Entertainment company. Price is high.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },

  // ── Stock Deals: MYT4U Electronics ──
  // Real game: electronics company, no dividend, range $5-$30
  {
    id: 'sd-5',
    title: 'MYT4U Electronics - $5',
    deal: {
      type: 'stock',
      name: 'MYT4U Electronics',
      symbol: 'MYT4U',
      costPerShare: 5,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 30 },
      description: 'Electronics company. Stock is at the bottom of its range.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-6',
    title: 'MYT4U Electronics - $10',
    deal: {
      type: 'stock',
      name: 'MYT4U Electronics',
      symbol: 'MYT4U',
      costPerShare: 10,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 30 },
      description: 'Electronics company. Moderate price.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-7',
    title: 'MYT4U Electronics - $20',
    deal: {
      type: 'stock',
      name: 'MYT4U Electronics',
      symbol: 'MYT4U',
      costPerShare: 20,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 30 },
      description: 'Electronics company. Price is near the high end.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-8',
    title: 'MYT4U Electronics - $30',
    deal: {
      type: 'stock',
      name: 'MYT4U Electronics',
      symbol: 'MYT4U',
      costPerShare: 30,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 30 },
      description: 'Electronics company. Price is at the top.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },

  // ── Stock Deals: OK4U Drug Co. ──
  // Real game: pharmaceutical company, no dividend, range $5-$40
  {
    id: 'sd-9',
    title: 'OK4U Drug Co. - $1',
    deal: {
      type: 'stock',
      name: 'OK4U Drug Co.',
      symbol: 'OK4U',
      costPerShare: 1,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 40 },
      description: 'Pharmaceutical company. Stock is at a deep discount.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-10',
    title: 'OK4U Drug Co. - $5',
    deal: {
      type: 'stock',
      name: 'OK4U Drug Co.',
      symbol: 'OK4U',
      costPerShare: 5,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 40 },
      description: 'Pharmaceutical company. Stock is near its low.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-11',
    title: 'OK4U Drug Co. - $10',
    deal: {
      type: 'stock',
      name: 'OK4U Drug Co.',
      symbol: 'OK4U',
      costPerShare: 10,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 40 },
      description: 'Pharmaceutical company. Moderate price.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-12',
    title: 'OK4U Drug Co. - $30',
    deal: {
      type: 'stock',
      name: 'OK4U Drug Co.',
      symbol: 'OK4U',
      costPerShare: 30,
      dividendPerShare: 0,
      historicalPriceRange: { low: 5, high: 40 },
      description: 'Pharmaceutical company. Price is high.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },

  // ── Stock Deals: GRO4US Fund ──
  // Real game: mutual fund, no dividend, range $10-$30
  {
    id: 'sd-13',
    title: 'GRO4US Fund - $5',
    deal: {
      type: 'stock',
      name: 'GRO4US Fund',
      symbol: 'GRO4US',
      costPerShare: 5,
      dividendPerShare: 0,
      historicalPriceRange: { low: 10, high: 30 },
      description: 'Mutual fund. Price is below the typical range.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-14',
    title: 'GRO4US Fund - $10',
    deal: {
      type: 'stock',
      name: 'GRO4US Fund',
      symbol: 'GRO4US',
      costPerShare: 10,
      dividendPerShare: 0,
      historicalPriceRange: { low: 10, high: 30 },
      description: 'Mutual fund. Price is at the low end of its range.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-15',
    title: 'GRO4US Fund - $20',
    deal: {
      type: 'stock',
      name: 'GRO4US Fund',
      symbol: 'GRO4US',
      costPerShare: 20,
      dividendPerShare: 0,
      historicalPriceRange: { low: 10, high: 30 },
      description: 'Mutual fund. Moderate price.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-16',
    title: 'GRO4US Fund - $40',
    deal: {
      type: 'stock',
      name: 'GRO4US Fund',
      symbol: 'GRO4US',
      costPerShare: 40,
      dividendPerShare: 0,
      historicalPriceRange: { low: 10, high: 30 },
      description: 'Mutual fund. Price is well above the typical range.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },

  // ── Stock Split Deals ──
  {
    id: 'sd-17',
    title: 'ON2U Stock Split 2-for-1!',
    deal: {
      type: 'stockSplit',
      name: 'ON2U Inc.',
      symbol: 'ON2U',
      splitRatio: 2,
      description: 'ON2U announces a 2-for-1 stock split. Your shares double, price per share halves.',
      rule: 'All players holding ON2U stock have their shares doubled and cost per share halved.',
    },
  },
  {
    id: 'sd-18',
    title: 'MYT4U Reverse Split 1-for-2!',
    deal: {
      type: 'stockSplit',
      name: 'MYT4U Electronics',
      symbol: 'MYT4U',
      splitRatio: 0.5,
      description: 'MYT4U announces a 1-for-2 reverse stock split. Your shares halve, price per share doubles.',
      rule: 'All players holding MYT4U stock have their shares halved and cost per share doubled.',
    },
  },

  // ── Real Estate Small Deals ──
  // Based on actual Cashflow 101 small deal real estate cards
  {
    id: 'sd-19',
    title: '3Br/2Ba House - Great Deal',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba House - Great Deal',
      cost: 35000,
      mortgage: 33000,
      downPayment: 2000,
      cashFlow: 220,
      description: 'Seller is motivated. Great cash flow for a low down payment.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-20',
    title: '2Br/1Ba House - Starter Home',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '2Br/1Ba House - Starter Home',
      cost: 50000,
      mortgage: 45000,
      downPayment: 5000,
      cashFlow: 100,
      description: 'Small starter home in a quiet neighborhood.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-21',
    title: '2Br/1Ba House - Near Schools',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '2Br/1Ba House - Near Schools',
      cost: 40000,
      mortgage: 36000,
      downPayment: 4000,
      cashFlow: 140,
      description: 'Good location near schools. Solid rental income.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-22',
    title: '2Br/1Ba House - Good Neighborhood',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '2Br/1Ba House - Good Neighborhood',
      cost: 40000,
      mortgage: 35000,
      downPayment: 5000,
      cashFlow: 220,
      description: 'Older home in a stable neighborhood. Tenant already in place.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-23',
    title: '3Br/2Ba House - Fixer Upper',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba House - Fixer Upper',
      cost: 50000,
      mortgage: 47000,
      downPayment: 3000,
      cashFlow: 100,
      description: 'Needs some work but priced below market value.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-24',
    title: '3Br/2Ba House - Family Home',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba House - Family Home',
      cost: 65000,
      mortgage: 60000,
      downPayment: 5000,
      cashFlow: 160,
      description: 'Nice family home in a growing area.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-25',
    title: '3Br/2Ba House - Bargain',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba House - Bargain',
      cost: 50000,
      mortgage: 46000,
      downPayment: 4000,
      cashFlow: 200,
      description: 'Owner relocating. Good cash flow opportunity.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-26',
    title: '2Br/1Ba House - Quick Sale',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '2Br/1Ba House - Quick Sale',
      cost: 45000,
      mortgage: 43000,
      downPayment: 2000,
      cashFlow: 250,
      description: 'Foreclosure property. Great deal for the savvy buyer.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-27',
    title: '2Br/1Ba House - Negative Cash Flow',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '2Br/1Ba House - Overpriced',
      cost: 60000,
      mortgage: 55000,
      downPayment: 5000,
      cashFlow: -100,
      description: 'High mortgage payments. This deal costs you money each month.',
      rule: 'Pay the down payment from your savings. Warning: negative cash flow!',
    },
  },
  {
    id: 'sd-28',
    title: '2Br/1Ba House - No Money Down',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '2Br/1Ba House - No Money Down',
      cost: 50000,
      mortgage: 50000,
      downPayment: 0,
      cashFlow: 100,
      description: 'Owner-financed. No down payment needed but fully mortgaged.',
      rule: 'No down payment required. Full amount is mortgaged.',
    },
  },
  {
    id: 'sd-29',
    title: '2Br/1Ba House - Break Even',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '2Br/1Ba House - Break Even',
      cost: 40000,
      mortgage: 39000,
      downPayment: 1000,
      cashFlow: 0,
      description: 'Low down payment but rents barely cover the mortgage.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-30',
    title: '2Br/1Ba House - Solid Investment',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '2Br/1Ba House - Solid Investment',
      cost: 55000,
      mortgage: 50000,
      downPayment: 5000,
      cashFlow: 160,
      description: 'Well-maintained property in a stable area.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
];
