import type { SmallDealCard } from '../types/index.js';

export const SMALL_DEAL_CARDS: SmallDealCard[] = [
  // ── Stock Deals ──
  {
    id: 'sd-1',
    title: 'ON2U Inc.',
    deal: {
      type: 'stock',
      name: 'ON2U Inc.',
      symbol: 'ON2U',
      costPerShare: 1,
      dividendPerShare: 0,
      historicalPriceRange: { low: 1, high: 30 },
      description: 'Biotech startup. No earnings yet but promising drug trials.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-2',
    title: 'MYT4U Corp.',
    deal: {
      type: 'stock',
      name: 'MYT4U Corp.',
      symbol: 'MYT4U',
      costPerShare: 5,
      dividendPerShare: 0,
      historicalPriceRange: { low: 1, high: 30 },
      description: 'Internet media company. High growth but no profits yet.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-3',
    title: 'OK4U Drug Co.',
    deal: {
      type: 'stock',
      name: 'OK4U Drug Co.',
      symbol: 'OK4U',
      costPerShare: 10,
      dividendPerShare: 0.20,
      historicalPriceRange: { low: 5, high: 40 },
      description: 'Pharmaceutical company with steady generic drug sales.',
      rule: 'You may purchase as many shares as you can afford. Pays $0.20/share dividend each turn.',
    },
  },
  {
    id: 'sd-4',
    title: 'GRO4US Corp.',
    deal: {
      type: 'stock',
      name: 'GRO4US Corp.',
      symbol: 'GRO4US',
      costPerShare: 20,
      dividendPerShare: 0.50,
      historicalPriceRange: { low: 10, high: 60 },
      description: 'Large consumer goods company. Reliable earnings and dividends.',
      rule: 'You may purchase as many shares as you can afford. Pays $0.50/share dividend each turn.',
    },
  },
  {
    id: 'sd-5',
    title: 'CHEAP2GT Mining',
    deal: {
      type: 'stock',
      name: 'CHEAP2GT Mining',
      symbol: 'CHEAP2GT',
      costPerShare: 2,
      dividendPerShare: 0,
      historicalPriceRange: { low: 1, high: 20 },
      description: 'Small gold mining company. Volatile price swings.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-6',
    title: 'TOYRU Electronics',
    deal: {
      type: 'stock',
      name: 'TOYRU Electronics',
      symbol: 'TOYRU',
      costPerShare: 7,
      dividendPerShare: 0,
      historicalPriceRange: { low: 2, high: 35 },
      description: 'Consumer electronics startup with a popular new gadget.',
      rule: 'You may purchase as many shares as you can afford. No dividend.',
    },
  },
  {
    id: 'sd-7',
    title: 'FRYK Food Inc.',
    deal: {
      type: 'stock',
      name: 'FRYK Food Inc.',
      symbol: 'FRYK',
      costPerShare: 15,
      dividendPerShare: 0.30,
      historicalPriceRange: { low: 8, high: 45 },
      description: 'Fast food franchise company with steady growth.',
      rule: 'You may purchase as many shares as you can afford. Pays $0.30/share dividend each turn.',
    },
  },
  {
    id: 'sd-8',
    title: 'SLRP Auto Parts',
    deal: {
      type: 'stock',
      name: 'SLRP Auto Parts',
      symbol: 'SLRP',
      costPerShare: 25,
      dividendPerShare: 0.40,
      historicalPriceRange: { low: 15, high: 55 },
      description: 'Auto parts manufacturer and distributor.',
      rule: 'You may purchase as many shares as you can afford. Pays $0.40/share dividend each turn.',
    },
  },

  // ── Real Estate Deals ──
  {
    id: 'sd-9',
    title: '2Br/1Ba House - Good Neighborhood',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '2Br/1Ba House - Good Neighborhood',
      cost: 65000,
      mortgage: 60000,
      downPayment: 5000,
      cashFlow: 160,
      description: 'Older 2-bedroom home in a stable neighborhood. Tenant already in place.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-10',
    title: '3Br/2Ba House - Fixer Upper',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba House - Fixer Upper',
      cost: 55000,
      mortgage: 50000,
      downPayment: 5000,
      cashFlow: 100,
      description: 'Needs some work but located near schools. Below market price.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-11',
    title: 'Small Condo - Near University',
    deal: {
      type: 'realEstate',
      subType: 'condo',
      name: 'Small Condo - Near University',
      cost: 40000,
      mortgage: 36000,
      downPayment: 4000,
      cashFlow: 100,
      description: '1-bedroom condo near a major university. Easy to rent to students.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-12',
    title: '2Br Condo - Downtown',
    deal: {
      type: 'realEstate',
      subType: 'condo',
      name: '2Br Condo - Downtown',
      cost: 60000,
      mortgage: 54000,
      downPayment: 6000,
      cashFlow: 140,
      description: 'Modern condo in walkable downtown area. High rental demand.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-13',
    title: 'Starter Home - Suburbs',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: 'Starter Home - Suburbs',
      cost: 80000,
      mortgage: 72000,
      downPayment: 8000,
      cashFlow: 200,
      description: '3Br/1Ba ranch-style home in quiet suburb. Newly renovated kitchen.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-14',
    title: 'Duplex - Working Class Area',
    deal: {
      type: 'realEstate',
      subType: 'duplex',
      name: 'Duplex - Working Class Area',
      cost: 80000,
      mortgage: 72000,
      downPayment: 8000,
      cashFlow: 250,
      description: 'Brick duplex with two 2Br/1Ba units. Both units rented.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-15',
    title: 'Duplex - Near Hospital',
    deal: {
      type: 'realEstate',
      subType: 'duplex',
      name: 'Duplex - Near Hospital',
      cost: 120000,
      mortgage: 108000,
      downPayment: 12000,
      cashFlow: 350,
      description: 'Two-unit duplex near major hospital. Attracts medical workers as tenants.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-16',
    title: '3Br/2Ba House - Great Deal',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '3Br/2Ba House - Great Deal',
      cost: 50000,
      mortgage: 47000,
      downPayment: 3000,
      cashFlow: 50,
      description: 'Seller is motivated. Lower-income area but rents are stable.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-17',
    title: 'Condo - Beachside',
    deal: {
      type: 'realEstate',
      subType: 'condo',
      name: 'Condo - Beachside',
      cost: 75000,
      mortgage: 68000,
      downPayment: 7000,
      cashFlow: 160,
      description: '1Br condo one block from the beach. Great for vacation rentals.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-18',
    title: '4Br/2Ba House - Family Home',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: '4Br/2Ba House - Family Home',
      cost: 140000,
      mortgage: 120000,
      downPayment: 20000,
      cashFlow: 400,
      description: 'Large family home in top school district. Premium rental rates.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-19',
    title: 'Duplex - College Town',
    deal: {
      type: 'realEstate',
      subType: 'duplex',
      name: 'Duplex - College Town',
      cost: 100000,
      mortgage: 90000,
      downPayment: 10000,
      cashFlow: 300,
      description: 'Two-unit property walking distance to campus. Always fully occupied.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },

  // ── Small Business Deals ──
  {
    id: 'sd-20',
    title: 'Vending Machine Route',
    deal: {
      type: 'business',
      name: 'Vending Machine Route',
      cost: 6000,
      mortgage: 0,
      downPayment: 6000,
      cashFlow: 100,
      description: 'Package of 5 vending machines in office buildings. Passive income.',
      rule: 'Pay the full cost from your savings to start this business.',
    },
  },
  {
    id: 'sd-21',
    title: 'Online Store Startup',
    deal: {
      type: 'business',
      name: 'Online Store Startup',
      cost: 8000,
      mortgage: 0,
      downPayment: 8000,
      cashFlow: 150,
      description: 'E-commerce store selling specialty items. Low overhead, growing customer base.',
      rule: 'Pay the full cost from your savings to start this business.',
    },
  },
  {
    id: 'sd-22',
    title: 'Laundromat Partnership',
    deal: {
      type: 'business',
      name: 'Laundromat Partnership',
      cost: 30000,
      mortgage: 20000,
      downPayment: 10000,
      cashFlow: 250,
      description: 'Buy into an existing laundromat. 50/50 partnership.',
      rule: 'Pay the down payment from your savings. Mortgage on business equipment.',
    },
  },
  {
    id: 'sd-23',
    title: 'Mobile Car Wash Business',
    deal: {
      type: 'business',
      name: 'Mobile Car Wash Business',
      cost: 5000,
      mortgage: 0,
      downPayment: 5000,
      cashFlow: 80,
      description: 'Mobile detailing equipment and established client list.',
      rule: 'Pay the full cost from your savings to start this business.',
    },
  },
  {
    id: 'sd-24',
    title: 'Food Truck',
    deal: {
      type: 'business',
      name: 'Food Truck',
      cost: 45000,
      mortgage: 30000,
      downPayment: 15000,
      cashFlow: 350,
      description: 'Fully equipped food truck with prime downtown parking permit.',
      rule: 'Pay the down payment from your savings. Loan covers the truck.',
    },
  },
  {
    id: 'sd-25',
    title: 'Coin-Op Car Wash',
    deal: {
      type: 'business',
      name: 'Coin-Op Car Wash',
      cost: 50000,
      mortgage: 35000,
      downPayment: 15000,
      cashFlow: 300,
      description: 'Self-serve car wash on a busy road. Minimal staffing required.',
      rule: 'Pay the down payment from your savings. Mortgage on equipment and lease.',
    },
  },
  {
    id: 'sd-26',
    title: 'House - Foreclosure Special',
    deal: {
      type: 'realEstate',
      subType: 'house',
      name: 'House - Foreclosure Special',
      cost: 45000,
      mortgage: 43000,
      downPayment: 2000,
      cashFlow: 75,
      description: 'Bank-owned 2Br/1Ba. Needs paint and carpet but structurally sound.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-27',
    title: 'ON2U Stock Split!',
    deal: {
      type: 'stock',
      name: 'ON2U Inc.',
      symbol: 'ON2U',
      costPerShare: 3,
      dividendPerShare: 0,
      historicalPriceRange: { low: 1, high: 30 },
      description: 'ON2U announces promising results. Stock rallying.',
      rule: 'You may purchase as many shares as you can afford at $3 per share. No dividend.',
    },
  },
  {
    id: 'sd-28',
    title: 'MYT4U Going Up!',
    deal: {
      type: 'stock',
      name: 'MYT4U Corp.',
      symbol: 'MYT4U',
      costPerShare: 10,
      dividendPerShare: 0,
      historicalPriceRange: { low: 1, high: 30 },
      description: 'MYT4U lands major advertising contract. Revenue surging.',
      rule: 'You may purchase as many shares as you can afford at $10 per share. No dividend.',
    },
  },
  {
    id: 'sd-29',
    title: 'Studio Condo - Bargain',
    deal: {
      type: 'realEstate',
      subType: 'condo',
      name: 'Studio Condo - Bargain',
      cost: 30000,
      mortgage: 27000,
      downPayment: 3000,
      cashFlow: 60,
      description: 'Tiny studio condo. Owner relocating and needs a quick sale.',
      rule: 'Pay the down payment from your savings to purchase this property.',
    },
  },
  {
    id: 'sd-30',
    title: 'Pet Grooming Franchise',
    deal: {
      type: 'business',
      name: 'Pet Grooming Franchise',
      cost: 25000,
      mortgage: 15000,
      downPayment: 10000,
      cashFlow: 200,
      description: 'Franchise location in a pet-friendly neighborhood. Includes training and equipment.',
      rule: 'Pay the down payment from your savings. Franchise loan covers the rest.',
    },
  },
];
